### ISSUE TITLE
システムアーキテクチャ設計

### ISSUE THREAD

**Issue by takashno** [SE-Garden/tms-management#1]
### 概要
システムをどのような構成のミドルウェアやソフトウェアを組み合わせて作り上げるかを設計

### 詳細
今回の開発では、非機能要件までは加味しなくても良い。  
最低限以下を決めること。  

- システム構成（想定で良い）
- ミドルウェアレベルに何を利用するか
- 冗長化構成はどのように行うか

#### 例
- フロントWEBは単純なWebサーバで公開（S3+Webhosting+CloudFront や Nginx、Apacheなど）
- バックエンドは全てREST-APIでありSpringBootのEmbeddedTomcatを利用
- バックエンドは全てステートレスとする
- 永続化としてDBにMySQLを利用する

**Comment by kawanof238** [comment]
マージされたのでクローズ
