### ISSUE TITLE
[server] データベース設計

### ISSUE THREAD

**Issue by kawanof238** [SE-Garden/tms-management#17]
### 概要
システムで扱うデータを分析し、データベースを設計する。

### 詳細
成果物としては、以下を想定。
- ER図
- DDL

**Comment by takashno** [comment]
今回RDBMSがMySQLだから、
データベース設計はMySQLWorkbenchを使うと楽にできる。
DDLを出力できるし。差分DDLも出せる。

**Comment by takashno** [comment]
完了している。
