### ISSUE TITLE
Reスケジューリング

### ISSUE THREAD

**Issue by takashno** [SE-Garden/tms-management#22]
### 概要
開発を完遂するべくスケジューリングをきちんと行う。  
まずは、このIssueにまとめてから個別Issueに起こすこととする。  
このIssueは打ち合わせの際のアジェンダ兼議事録にもなる。

|順序|タスク|担当|期限感|話す内容の事前準備が可能な人|
|:---|:---|:---|:---|:---|
|0|体制とゴールについて||||
|1|機能一覧化|||河野・千木良|
|2|機能を少し細かく検討||||
|3|画面一覧|||河野|
|4|API一覧|||千木良|
|6|開発環境の合わせ込み||||
|7|稼働環境の合わせ込み||||
|8|テストについての検討|||高島|
|9|タスク出し||||
|10|スケジューリング||||

#### 体制

|人|役割|説明|
|:---|:---|:---|
|高島|管理,レビュー,開発|サーバーサイド系相談役、テスト対応|
|河野|開発|開発者|
|千木良|開発|開発者|
|大國|開発|開発者|
|玉造|管理,レビュー|開発系相談役|
|保坂|管理,レビュー|AWS系相談役|
|須崎|アドバイザー|フロントエンド系相談役|

#### ゴール

少なくとも、Excelの代わりを担うWebシステムを作り上げること。
それはシステムを利用して運用できるレベルであること。

**Comment by kawanof238** [comment]
# 機能一覧化

## ログイン
- 対象
未認証ユーザー

- 機能
ユーザーを認証する機能です。

## 報告書一覧
- 対象
全ログインユーザー

- 機能
ユーザーに関係する報告書を一覧表示します。
ユーザーによって表示内容が異なります。
上司、トレーナーは報告書を差し戻すことができます。

|ロール|表示内容|
|:---|:---|
|上司|提出された部下のOJT報告書が表示されます|
|トレーナー|提出されたトレーニーのOJT報告書が表示されます|
|トレーニー|自分の全OJT報告書が表示されます|

## 報告書作成
- 対象
全ログインユーザー

- 機能
OJT報告書を作成する機能です。  
作成対象の年月を指定し、OJT報告書の中身を記載します。  
記載した内容は一時保存したり、上司・トレーナーに提出できます。

## 報告書編集
- 対象
全ログインユーザー

- 機能
OJT報告書を編集する機能です。  
作成済みのOJT報告書を選択して、OJT報告書の中身を編集します。  
記載した内容は一時保存したり、上司・トレーナーに提出できます。
上司、トレーナーは報告書を差し戻すことができます。

## 報告書検索
- 対象
全ログインユーザー

- 機能
OJT報告書を検索する機能です。  

# 画面一覧
全１０画面

外部ホーム	https://se-garden.github.io/tms-mockup/mockup/index.html
ログイン	https://se-garden.github.io/tms-mockup/mockup/login.html
内部ホーム	https://se-garden.github.io/tms-mockup/mockup/internal/top.html
OJT 報告書一覧 対象選択	https://se-garden.github.io/tms-mockup/mockup/internal/viewList.html
OJT 報告書一覧 内容表示	https://se-garden.github.io/tms-mockup/mockup/internal/view.html
OJT 報告書作成 年月設定	https://se-garden.github.io/tms-mockup/mockup/internal/createSelect.html
OJT 報告書作成 内容作成	https://se-garden.github.io/tms-mockup/mockup/internal/create.html
OJT 報告書編集 対象選択	https://se-garden.github.io/tms-mockup/mockup/internal/editSelect.html
OJT 報告書編集 内容編集	https://se-garden.github.io/tms-mockup/mockup/internal/edit.html
OJT 報告書検索	https://se-garden.github.io/tms-mockup/mockup/internal/search.html?

**Comment by takashno** [comment]
- バックエンド開発方針
  - OpenAPI3 を利用
  - MyBatisGeneratorを利用
  - 極力コーディング量を減らす
  - 認証はSpringSecurityによるLDAP
  - ログインはバックエンドにログインAPIを設ける。
  - SESSIONID払い出しCookieで返却
  - 認証情報はRedisで保有

**Comment by takashno** [comment]
この想定で走っているため、クローズ。
