### ISSUE TITLE
ソフトウェアアーキテクチャ（フロントエンド）

### ISSUE THREAD

**Issue by takashno** [SE-Garden/tms-management#3]
### 概要
フロントエンドのソフトウェアアーキテクチャを決定する。  
簡単にいうと、何を使ってどう作るか？というところ。

### 詳細
フロントエンドの技術はかなり進化が早いですが、ここ数年落ち着きだしている。  
Googleで調べただけでも、かなり多くの技術・思想を見つけることができる。  
その中で今回利用したいものを決定する。  

全体の合意が取れればよいので、  
自分が使ってみたいものを使うのがモチベーションを保つには重要だと思われる。

**Comment by kawanof238** [comment]
マージされたのでクローズ
