### ISSUE TITLE
ソフトウェアアーキテクチャ（サーバーサイド）

### ISSUE THREAD

**Issue by takashno** [SE-Garden/tms-management#4]
### 概要
サーバーサイドのソフトウェアアーキテクチャを決定する。  
簡単にいうと、何を使ってどう作るか？というところ。

### 詳細
Serverlessを採用してもよいが、  
極力業務に直結した方が今回も目的としては良いかもしれない。  
どうしてもSpring関連の技術はこれからも付き合うため、知っておいて損はない。  
あとで変えることももちろん可能。  
  
ただし、全体と合意が取れれば他技術で代替することも問題ない。

**Comment by kawanof238** [comment]
マージされたのでクローズ
