### ISSUE TITLE
開発方法決定

### ISSUE THREAD

**Issue by takashno** [SE-Garden/tms-management#5]
### 概要
開発方法としてどのような手段を用いるかを決定する。

### 詳細
細かいが、以下を考えたり決定しておくと複数人で開発すると  
トラブルシュートも共有できたりするので割と助かる。

- 使用するIDE（Eclipse? IntelliJ? VSCode?）
- 静的解析（Lint系）
- ブランチ戦略（GitHub Flow以外がいいなら決める）
- ローカル環境構築方法（Docker?）

**Comment by kawanof238** [comment]
マージしました。
